### ISSUE TITLE
Cannot load dataset

### ISSUE THREAD

**Issue by xiaolizhang77** [AutoVision-cloud/SSL-Lanes#1]
```py
(/home/li/SSL-Lanes/.envSSl) [root@gpu14 final_baseline]# python preprocess_data.py -m lanegcn
lanegcn
Traceback (most recent call last):
  File "preprocess_data.py", line 415, in <module>
    main()
  File "preprocess_data.py", line 56, in main
    val(config)
  File "preprocess_data.py", line 118, in val
    dataset = Dataset(config["val_split"], config, train=False)
  File "/home/li/SSL-Lanes/baseline/final_baseline/data.py", line 29, in __init__
    self.am = ArgoverseMap()
  File "/home/li/SSL-Lanes/argoverse-api/argoverse/map_representation/map_api.py", line 71, in __init__
    self.city_rasterized_da_roi_dict = self.build_city_driveable_area_roi_index()
  File "/home/li/SSL-Lanes/argoverse-api/argoverse/map_representation/map_api.py", line 197, in build_city_driveable_area_roi_index
    city_rasterized_da_roi_dict[city_name]["da_mat"] = np.load(npy_fpath)
  File "/home/li/SSL-Lanes/.envSSl/lib/python3.7/site-packages/numpy/lib/npyio.py", line 440, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/li/SSL-Lanes/.envSSl/lib/python3.7/site-packages/numpy/lib/format.py", line 771, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 12910464 into shape (3043,4259)
```
Hi, I want to preprocess the data set, but run into this problem. Can you tell me how to solve it？
Thank you,

**Comment by AutoVision-cloud** [comment]
Hi, please consider downloading the preprocessed data:
```
wget https://yun.sfo2.cdn.digitaloceanspaces.com/public/lanegcn/test_test.p
wget https://yun.sfo2.cdn.digitaloceanspaces.com/public/lanegcn/train_crs_dist6_angle90.p
wget https://yun.sfo2.cdn.digitaloceanspaces.com/public/lanegcn/val_crs_dist6_angle90.p

```

**Comment by backkon** [comment]
Hello, where can I download the preprocessed data 'train_intention.p'?
